#ifndef _STM32YYXX_LL_H_
#define _STM32YYXX_LL_H_
/* LL raised several warnings, ignore them */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wstrict-aliasing"

/* Include Low Layers drivers */
//#include "stm32f1xx_ll_adc.h"
#include "stm32f1xx_ll_adc.h"
//#include "stm32f1xx_ll_bdma.h"
#include "stm32f1xx_ll_bus.h"
//#include "stm32f1xx_ll_comp.h"
//#include "stm32f1xx_ll_cordic.h"
#include "stm32f1xx_ll_cortex.h"
#include "stm32f1xx_ll_crc.h"
//#include "stm32f1xx_ll_crs.h"
#include "stm32f1xx_ll_dac.h"
//#include "stm32f1xx_ll_delayblock.h"
#include "stm32f1xx_ll_dma.h"
//#include "stm32f1xx_ll_dma2d.h"
//#include "stm32f1xx_ll_dmamux.h"
#include "stm32f1xx_ll_exti.h"
//#include "stm32f1xx_ll_fmac.h"
//#include "stm32f1xx_ll_fmc.h"
//#include "stm32f1xx_ll_fsmc.h"
#include "stm32f1xx_ll_gpio.h"
//#include "stm32f1xx_ll_hrtim.h"
//#include "stm32f1xx_ll_hsem.h"
#include "stm32f1xx_ll_i2c.h"
//#include "stm32f1xx_ll_ipcc.h"
#include "stm32f1xx_ll_iwdg.h"
//#include "stm32f1xx_ll_lptim.h"
//#include "stm32f1xx_ll_lpuart.h"
//#include "stm32f1xx_ll_mdma.h"
//#include "stm32f1xx_ll_opamp.h"
//#include "stm32f1xx_ll_pka.h"
#include "stm32f1xx_ll_pwr.h"
#include "stm32f1xx_ll_rcc.h"
//#include "stm32f1xx_ll_rng.h"
#include "stm32f1xx_ll_rtc.h"
#include "stm32f1xx_ll_sdmmc.h"
#include "stm32f1xx_ll_spi.h"
//#include "stm32f1xx_ll_swpmi.h"
#include "stm32f1xx_ll_system.h"
#include "stm32f1xx_ll_tim.h"
//#include "stm32f1xx_ll_ucpd.h"
#include "stm32f1xx_ll_usart.h"
#include "stm32f1xx_ll_usb.h"
#include "stm32f1xx_ll_utils.h"
#include "stm32f1xx_ll_wwdg.h"
#pragma GCC diagnostic pop
#endif /* _STM32YYXX_LL_H_ */
